config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get 'login', to: 'login#index', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  post 'telegram/updates', to: 'telegram#create', defaults: { format: :json }

  get 'auth/:provider/callback', to: 'sessions#create'

  resources :account, only: [:index]

  get 'zones/import', to: 'zones#new_import'
  post 'zones/import', to: 'zones#create_import'
  resources :zones, except: [:edit, :update], param: :root, constraints: { root: %r{[^/]+} } do
    get 'delete', on: :member
  end

  resources :credentials, except: [:edit, :delete]

  namespace :integrations do
    get 'telegram/callback', to: 'telegram#callback'
    delete 'telegram', to: 'telegram#destroy'
  end
end

app/models/zone.rb
class Zone < ApplicationRecord
  belongs_to :user
  belongs_to :credential, optional: true

  before_save :trim_trailing_dot_from_root
  before_create :generate_route53_create_hosted_zone_caller_reference

  def to_param
    root
  end

  def records
    ListRecords.call(self)
  end

  private

  def generate_route53_create_hosted_zone_caller_reference
    self.route53_create_hosted_zone_caller_reference ||= SecureRandom.uuid
  end

  def trim_trailing_dot_from_root
    self.root = root.delete_suffix('.')
  end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_current_zone, except: [:index, :new, :create, :new_import, :create_import]

  def index
    @zones = current_user.zones
  end

  def new
    @credentials = current_user.credentials
  end

  def new_import
    @import_zone_form = ImportZoneForm.new
  end

  def create_import
    @import_zone_form = ImportZoneForm.new(import_params)
    return render :new_import if @import_zone_form.invalid?

    credential = current_user.credentials.find(@import_zone_form.credential_id)
    @zone = ImportZone.call(current_user, @import_zone_form.hosted_zone_id, credential)
    redirect_to @zone
  rescue Credential::AccessDenied
    flash.alert = 'The credentials you specified do not have the right permissions to import this zone.'
    render :new_import
  rescue ImportZone::NoSuchHostedZone
    flash.alert = 'No such hosted zone!'
    render :new_import
  end

  def create
    root = create_params.require(:root).delete_suffix('.')
    managed = create_params[:managed] != 'false'

    if managed && !Features.enabled?(:managed_zones)
      flash.alert = 'Managed zones are currently not enabled!'
      return render :new
    end

    if !managed && create_params[:credential_id].blank?
      flash.alert = 'You must specify a credential to use when creating an unmanaged zone.'
      return render :new
    end

    credential = Credential.find_by(id: create_params.require(:credential_id).to_i, user: current_user) unless managed
    if !managed && credential.nil?
      flash.alert = 'Credentials not found!'
      return render :new
    end

    zone = CreateZone.call(current_user, root, credential)
    redirect_to zone
  rescue CreateZone::ZoneAlreadyExists
    flash.alert = 'You have already created a zone with that root!'
    redirect_to new_zone_path
  rescue Credential::AccessDenied
    flash.alert = 'The selected credentials were rejected by AWS. Is your policy set up correctly?'
    render :new
  rescue CreateZone::InvalidDomainName
    flash.alert = 'The provided zone root is invalid!'
    render :new
  end

  def delete
  end

  def destroy
    begin
      deleted = DeleteZone.call(@zone)
    rescue DeleteZone::ZoneNotEmpty
      flash.alert = 'Your zone could not be deleted because it contains records other than the default SOA and NS records.'
      return redirect_to(@zone)
    end
    unless deleted
      flash.alert = 'An unknown error occurred while trying to delete your zone.'
      return redirect_to(@zone)
    end
    flash.notice = 'Zone deleted!' if deleted
    redirect_to zones_path
  end

  def show
  end

  private

  def create_params
    params.permit(:root, :managed, :credential_id)
  end

  def import_params
    params.require(:import_zone_form).permit(:hosted_zone_id, :credential_id)
  end

  def set_current_zone
    @zone = current_user.zones.find_by(root: params[:root])
    if @zone.nil?
      flash.alert = 'Zone not found!'
      redirect_to(zones_path)
    end
  end
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/zones/delete.html.erb
<h1><%= @zone.root %></h1>

<p>Are you sure you want to delete this zone?</p>

<div>
  <%= link_to 'Back', @zone, class: 'btn btn-primary' %>
  <%= link_to 'Delete zone', @zone, method: :delete, class: 'btn btn-danger' %>
</div>

app/views/zones/index.html.erb
<% content_for :breadcrumbs do %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Zones</li>
    </ol>
  </nav>
<% end %>

<h1>My Zones</h1>

<div>
  <a href="<%= new_zone_path %>" class="btn btn-primary">Create new zone</a>
  <a href="<%= zones_import_path %>" class="btn btn-primary">Import zone</a>
</div>

<div class="my-3">
  <div class="list-group">
    <% if @zones.empty? %>
      <div class="list-group-item">You haven't created any zones yet!</div>
    <% else %>
      <% @zones.each do |zone| %>
        <a href="<%= zone_path(zone) %>" class="list-group-item list-group-item-action"><%= zone.root %></a>
      <% end %>
    <% end %>
  </div>
</div>

app/views/zones/new.html.erb
<% content_for :breadcrumbs do %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="<%= zones_path %>">Zones</a></li>
      <li class="breadcrumb-item active" aria-current="page">New zone</li>
    </ol>
  </nav>
<% end %>

<h1>New zone</h1>
<%= bootstrap_form_tag url: zones_path do |f| %>
  <%= f.text_field :root, placeholder: 'example.com' %>

  <%= f.form_group :managed, label: { text: "Managed by NekoDNS?" }, help: 'Choose "No" to have NekoDNS create a DNS zone using one of your AWS IAM roles.' do %>
    <% if Features.enabled?(:managed_zones) %>
      <%= f.radio_button :managed, 'true', label: "Yes", checked: true %>
      <%= f.radio_button :managed, 'false', label: "No" %>
    <% else %>
      <%= f.radio_button :managed, 'true', label: "Yes", disabled: !Features.enabled?(:managed_zones) %>
      <%= f.radio_button :managed, 'false', label: "No", checked: true %>
    <% end %>
  <% end %>

  <% if current_user.credentials.empty? %>
    <%= f.select :credential_id, ['No credentials available', nil], { label: 'Credentials' }, { disabled: true } %>
  <% else %>
    <%= f.select :credential_id, options_from_collection_for_select(current_user.credentials, :id, :name), { label: 'Credentials', help: 'Not applicable for managed zones.' } %>
  <% end %>

  <%= f.primary 'Create' %>
<% end %>

app/views/zones/new_import.html.erb
<% content_for :breadcrumbs do %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="<%= zones_path %>">Zones</a></li>
      <li class="breadcrumb-item active" aria-current="page">Import zone</li>
    </ol>
  </nav>
<% end %>

<h1>Import zone</h1>
<p class="text-muted">Import a Route53 Hosted Zone</p>

<%= bootstrap_form_for @import_zone_form, url: 'import' do |f| %>
  <%= f.text_field :hosted_zone_id, label: 'Hosted zone ID' %>

  <% if current_user.credentials.empty? %>
    <%= f.select :credential_id, ['No credentials available', nil], { label: 'Credentials', help: 'Must have access to the specified zone' }, { disabled: true } %>
  <% else %>
    <%= f.select :credential_id, options_from_collection_for_select(current_user.credentials, :id, :name), { label: 'Credentials', help: 'Must have access to the specified zone' } %>
  <% end %>

  <%= f.primary 'Import zone' %>
<% end %>

app/views/zones/show.html.erb
<% content_for :breadcrumbs do %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="<%= zones_path %>">Zones</a></li>
      <li class="breadcrumb-item active" aria-current="page"><%= @zone.root %></li>
    </ol>
  </nav>
<% end %>

<h1><%= @zone.root %></h1>

<div>
  <%= link_to 'Delete zone', delete_zone_path(@zone), class: 'btn btn-danger' %>
</div>

<h2>Records</h2>

<table class="table">
  <thead>
  <tr>
    <th scope="col">Type</th>
    <th scope="col">Name</th>
    <th scope="col">Value</th>
    <th scope="col">TTL</th>
  </tr>
  </thead>
  <tbody>
  <% @zone.records.each do |record| %>
    <tr>
      <td><%= record.type %></td>
      <td><%= record.name %></td>
      <td><%= record.value %></td>
      <td><%= record.ttl %></td>
    </tr>
  <% end %>
  </tbody>
</table>