config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get 'login', to: 'login#index', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  post 'telegram/updates', to: 'telegram#create', defaults: { format: :json }

  get 'auth/:provider/callback', to: 'sessions#create'

  resources :account, only: [:index]

  get 'zones/import', to: 'zones#new_import'
  post 'zones/import', to: 'zones#create_import'
  resources :zones, except: [:edit, :update], param: :root, constraints: { root: %r{[^/]+} } do
    get 'delete', on: :member
  end

  resources :credentials, except: [:edit, :delete]

  namespace :integrations do
    get 'telegram/callback', to: 'telegram#callback'
    delete 'telegram', to: 'telegram#destroy'
  end
end

app/models/credential.rb
class Credential < ApplicationRecord
  belongs_to :user
  attr_accessor :signed_external_id
  validates :name, :arn, :external_id, presence: true
  validate :external_id_verified

  def generate_external_id
    self.external_id = SecureRandom.uuid
    @signed_external_id = verifier.generate(external_id, purpose: :external_id)
  end

  def external_id_verified
    if verifier.verified(signed_external_id, purpose: :external_id) != external_id
      errors.add(:external_id, 'invalid external ID')
    end
  end

  def self.human_attribute_name(attr, options = {})
    attr == 'external_id' ? 'External ID' : super
  end

  private

  def verifier
    @verifier ||= ActiveSupport::MessageVerifier.new(Rails.application.secret_key_base)
  end

  class AccessDenied < StandardError
  end
end

app/controllers/credentials_controller.rb
class CredentialsController < ApplicationController
  def index
    @credentials = current_user.credentials
  end

  def new
    @credential = Credential.new
    @credential.generate_external_id
  end

  def create
    @credential = Credential.create(credential_params.merge(user: current_user))
    return render :new unless @credential.errors.empty?
    redirect_to @credential
  end

  def show
    @credential = Credential.find(params[:id])
  end

  private

  def credential_params
    params.require(:credential).permit(:name, :external_id, :signed_external_id, :arn)
  end
end

app/helpers/credentials_helper.rb
module CredentialsHelper
end

app/views/credentials/index.html.erb
<% content_for :breadcrumbs do %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Credentials</li>
    </ol>
  </nav>
<% end %>

<h1>Credentials</h1>

<div>
  <a href="<%= new_credential_path %>" class="btn btn-primary">Add credential</a>
</div>

<div class="my-3">
  <div class="list-group">
    <% if @credentials.empty? %>
      <div class="list-group-item">You haven't added any credentials yet!</div>
    <% else %>
      <% @credentials.each do |credential| %>
        <a href="<%= credential_path(credential) %>" class="list-group-item list-group-item-action"><%= credential.name %></a>
      <% end %>
    <% end %>
  </div>
</div>

app/views/credentials/new.html.erb
<% content_for :breadcrumbs do %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="<%= credentials_path %>">Credentials</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add credential</li>
    </ol>
  </nav>
<% end %>

<h1>Add credential</h1>

<%= bootstrap_form_for(@credential) do |f| %>
  <%= f.text_field :name %>

  <p>Create a new IAM role for NekoDNS to use with a <a href="/documents/nekodns-iam-policy.json">suitable policy</a>
    attached. Specify "Another AWS account" as the
    trusted entity type and provide the following account ID and external ID
    (<a href="/images/create-iam-role-for-third-party.png">screenshot</a>):</p>

  <%= f.text_field :account_id, label: 'Account ID', value: Rails.configuration.aws_account_id, name: nil, readonly: true %>
  <%= f.text_field :external_id, label: 'External ID', value: @credential.external_id, readonly: true %>
  <%= f.hidden_field :signed_external_id, value: @credential.signed_external_id %>

  <%= f.text_field :arn, label: 'Role ARN', placeholder: 'arn:aws:iam::123456789012:role/RoleName' %>

  <%= f.primary 'Add credential' %>
<% end %>

app/views/credentials/show.html.erb
<% content_for :breadcrumbs do %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="<%= credentials_path %>">Credentials</a></li>
      <li class="breadcrumb-item active" aria-current="page"><%= @credential.name %></li>
    </ol>
  </nav>
<% end %>

<h1><%= @credential.name %></h1>

<div>
  <dl class="row">
    <dt class="col-sm-3">Role ARN</dt>
    <dd class="col-sm-9"><%= @credential.arn %></dd>
    <dt class="col-sm-3">External ID</dt>
    <dd class="col-sm-9"><%= @credential.external_id %></dd>
    <dt class="col-sm-3">Account ID</dt>
    <dd class="col-sm-9"><%= Rails.configuration.aws_account_id %></dd>
  </dl>
</div>