config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get 'login', to: 'login#index', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  post 'telegram/updates', to: 'telegram#create', defaults: { format: :json }

  get 'auth/:provider/callback', to: 'sessions#create'

  resources :account, only: [:index]

  get 'zones/import', to: 'zones#new_import'
  post 'zones/import', to: 'zones#create_import'
  resources :zones, except: [:edit, :update], param: :root, constraints: { root: %r{[^/]+} } do
    get 'delete', on: :member
  end

  resources :credentials, except: [:edit, :delete]

  namespace :integrations do
    get 'telegram/callback', to: 'telegram#callback'
    delete 'telegram', to: 'telegram#destroy'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_raven_context if ENV['SENTRY_DSN'].present?
  before_action :require_login
  helper_method :current_user

  def current_user
    return unless session[:user_id]

    @current_user ||= User.find(session[:user_id])
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def require_login
    unless current_user
      flash.alert = "You must be logged in to access this section"
      redirect_to login_url
    end
  end

  def set_raven_context
    Raven.user_context(id: session[:user_id])
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def oauth_path(provider)
    "/auth/#{provider}"
  end
end

app/views/application/_flash_messages.html.erb
<% if flash.alert %>
  <div class="alert alert-warning"><%= flash.alert %></div>
<% end %>
<% if flash.notice %>
  <div class="alert alert-primary"><%= flash.notice %></div>
<% end %>

app/views/application/_ga.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV['GA_TRACKING_ID'] %>"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    document.addEventListener('turbolinks:load', function(e) {
        gtag('config', '<%= ENV['GA_TRACKING_ID'] %>', {
            'page_location': e.data.url
        });
    });
</script>

app/views/application/_logged_in_indicator.html.erb
<ul class="navbar-nav">
  <li class="nav-item">
    <a href="<%= account_index_path %>" class="nav-link text-dark"><%= current_user.name %></a>
  </li>
  <li class="nav-item">
    <a href="<%= logout_path %>" class="nav-link">Logout</a>
  </li>
</ul>

app/views/application/_navbar.html.erb
<li class="nav-item">
  <a href="<%= zones_path %>" class="nav-link">My Zones</a>
</li>
<li class="nav-item">
  <a href="<%= credentials_path %>" class="nav-link">Credentials</a>
</li>