config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get 'login', to: 'login#index', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  post 'telegram/updates', to: 'telegram#create', defaults: { format: :json }

  get 'auth/:provider/callback', to: 'sessions#create'

  resources :account, only: [:index]

  get 'zones/import', to: 'zones#new_import'
  post 'zones/import', to: 'zones#create_import'
  resources :zones, except: [:edit, :update], param: :root, constraints: { root: %r{[^/]+} } do
    get 'delete', on: :member
  end

  resources :credentials, except: [:edit, :delete]

  namespace :integrations do
    get 'telegram/callback', to: 'telegram#callback'
    delete 'telegram', to: 'telegram#destroy'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <!-- Primary Meta Tags -->
    <title>NekoDNS — Chatops for your DNS records</title>
    <meta name="title" content="NekoDNS — Chatops for your DNS records">
    <meta name="description" content="NekoDNS integrates with your DNS provider to let you manage your domains on-the-go through your favourite instant messaging platform.">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= request.base_url %>">
    <meta property="og:title" content="NekoDNS — Chatops for your DNS records">
    <meta property="og:description" content="NekoDNS integrates with your DNS provider to let you manage your domains on-the-go through your favourite instant messaging platform.">
    <meta property="og:image" content="<%= request.base_url %>/NekoDNS.png">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="<%= request.base_url %>">
    <meta property="twitter:title" content="NekoDNS — Chatops for your DNS records">
    <meta property="twitter:description" content="NekoDNS integrates with your DNS provider to let you manage your domains on-the-go through your favourite instant messaging platform.">
    <meta property="twitter:image" content="<%= request.base_url %>/NekoDNS.png">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">

    <% if Rails.env.production? %>
      <%= render 'ga' %>
    <% end %>
  </head>

  <body>
  <nav class="navbar navbar-expand navbar-light bg-light">
    <div class="container">
      <a href="<%= root_path %>" class="navbar-brand">NekoDNS
        <small><span class="badge badge-secondary align-text-top">ALPHA</span></small>
      </a>

      <ul class="navbar-nav mr-auto">
        <% if current_user %>
          <%= render 'navbar' %>
        <% end %>
      </ul>

      <% if current_user %>
        <%= render 'logged_in_indicator' %>
      <% else %>
        <a href="<%= login_path %>" class="btn btn-outline-dark">Login</a>
      <% end %>
    </div>
  </nav>
  <main class="container my-3">
    <%= yield :breadcrumbs %>
    <%= render 'flash_messages' %>
    <%= yield %>
  </main>
  </body>
</html>